name: Playwright Tests

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every hour
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]


jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Set up Secrets
      run: echo "ENV=${{ secrets.ENV }}" >> $GITHUB_ENV
      shell: bash

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      env:
        ENV: ${{ secrets.ENV }}
        USER: ${{ secrets.USER }}
        PASS: ${{ secrets.PASS }}
      run: npx playwright test

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: time.txt
        retention-days: 30

    - name: Commit and Push Changes
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
        git add time.txt
        git commit -m "Update time.txt"
        git push --force

